[package]
name = "polywrap_client"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "1.0.1"
serde = "1.0.145"
thiserror = "1.0.37"
reqwest = "0.11.12"
rmp-serde = "1.1.1"
tokio = { version = "1", features = ["full"] }