[package]
name = "polywrap_plugin_macro"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0.105"
polywrap_core = { path = "../core" }

[lib]
proc-macro = true

[dev-dependencies]
serde_json = "1.0.87"