[package]
name = "polywrap_client_default_config"
description = "Default configuration for Polywrap Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
base64.workspace = true

polywrap_wasm = { version = "0.1.4-alpha.2" }
polywrap_resolvers = { version = "0.1.4-alpha.2" }
polywrap_client_builder = { version = "0.1.4-alpha.2" }
polywrap_core = { version = "0.1.4-alpha.2" }
polywrap_plugin = { version = "0.1.4-alpha.4", features = ["implementor"] }

fs_plugin_rs = { version  = "0.0.1-beta.1" }
http_plugin_rs = { version  = "0.0.1-beta.1" }