[package]
name = "polywrap_wasm"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
rmp-serde = "1.1.1"
rmpv = "1.0.0"
serde = "1.0.145"
thiserror = "1.0.37"
base64 = "0.13.0"
serde_json = "1.0.87"
wasmer = "3.1.1"
polywrap_core = {path = "../core"}
wrap_manifest_schemas = {path = "../manifest"}
polywrap_msgpack = {path = "../msgpack"}

[dev-dependencies]
polywrap_tests_utils = {path = "../tests-utils"}