[package]
name = "polywrap_wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "1.0.1"
serde = "1.0.145"
thiserror = "1.0.37"
reqwest = "0.11.12"
rmp-serde = "1.1.1"
async-trait = "0.1.57"
tokio = { version = "1", features = ["full"] }
polywrap_core = {path = "../core"}