[package]
name = "polywrap_ffi_c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
polywrap_client = {path = "../client"}
polywrap_plugin = {path = "../plugin"}
polywrap_wasm = {path = "../wasm"}
fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}
serde_json = "1.0.87"
libc = "0.2"
