[package]
name = "polywrap_tests_utils"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
polywrap_core = { path = "../core" }
async-trait = "0.1.57"
wrap_manifest_schemas = { path = "../manifest" }
futures = "0.3.24"

