[package]
name = "polywrap_client_builder"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
polywrap_core = {path = "../core"}
polywrap_resolvers = { path = "../resolvers" }
serde_json = "1.0.87"
serde = {version = "1.0.145", features = ["derive"]}
polywrap_plugin = {path ="../plugin"}
polywrap_wasm = {path = "../wasm"}
fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}
futures = "0.3.24"
base64 = "0.13.1"

[dev-dependencies]
polywrap_tests_utils = {path = "../tests-utils"}
tokio = { version = "1.3", features = ["full"] }