[package]
name = "polywrap_resolvers"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
regex = "1.6.0"
pathdiff = "0.2.1"
polywrap_core = {path = "../core"}
polywrap_wasm = {path = "../wasm"}
polywrap_msgpack = {path = "../msgpack"}
serde = "1.0.145"
